@include('include.dashboard.top')
@include('include.dashboard.header')
@include('include.dashboard.aside')
@yield('content')
@include('include.dashboard.modal')
@include('include.message')
@include('include.dashboard.footer')
@include('include.dashboard.footerjs')